; Zafuse - Multi INI File Content Analysis Software
; Zafuse - Italian Lang File.
; (C) Copyright 2025-2026, Eray Türkay.
; Publisher: Türkaysoft
; Project Type: Open Source
; License: MIT License
; Website: https://turkaysoft.com
; GitHub: https://github.com/turkaysoft/zafuse

[Main]
lang_name = Italian / Italy
lang_tag = it
translator = TS Translator Team
zafuse_version = v26.11

[HeaderMenu]
header_menu_settings = Impostazioni
header_menu_theme = Tema
header_menu_language = Lingua (Language)
header_menu_start = Inizio
header_analysis_mode = Modalità di analisi
header_menu_update = Controlla Aggiornamenti
header_menu_donate = Dona
header_menu_about = Informazioni

[HeaderThemes]
theme_light = Tema Chiaro
theme_dark = Tema Scuro
theme_system = Tema del sistema

[HeaderLangs]
lang_ar = Arabo (Arabic)
lang_zh = Chinese (Chinese)
lang_en = English (English)
lang_nl = Olandese (Dutch)
lang_fr = French (French)
lang_de = German (German)
lang_hi = Hindi (Hindi)
lang_it = Italiano (Italian)
lang_ja = Giapponese (Japanese)
lang_ko = Korean (Korean)
lang_pl = Polacco (Polish)
lang_pt = Portuguese (Portuguese)
lang_ru = Russian (Russian)
lang_es = Spanish (Spanish)
lang_tr = Turkish (Turkish)

[LangChange]
lang_change_notification = La lingua è stata cambiata.{0}Alcuni campi richiedono un riavvio del programma per cambiare la lingua.{1}Vuoi riavviare il programma adesso?

[HeaderViewMode]
header_view_mode_windowed = Finestra
header_view_mode_full_screen = Schermo Intero

[HeaderAnalysisMode]
has_placeholders = Segni di posizionamento
has_punctuation_marks = Segni di punteggiatura
has_nail_signs = Virgolette
has_numbers = Numeri
has_comment_lines = Righe di commento

[HeaderHelp]
header_help_info_notification = {0} è già aperto.

; MAIN
; ====================================================================

[ZafuseMain]
zm_t_analysis = {0} - Analisi in corso...
zm_b_add = Aggiungi cartella
zm_b_remove = Rimuovi cartella
zm_b_generate = Genera report
zm_b_add_msg = Seleziona la cartella contenente i file INI.
zm_drag_only_one_folder = Trascina solo una cartella alla volta, per favore.
zm_drag_not_folder = Trascina o seleziona solo una cartella.
zm_b_add_available_msg = La cartella selezionata è già stata aggiunta in precedenza.
zm_drag_ini_not_found = Questa cartella deve contenere almeno 2 file .ini.
zm_b_remove_select_msg = Seleziona una directory dalla lista a sinistra per eliminare una cartella.
zm_b_remove_default_msg = La cartella selezionata non può essere eliminata perché è una directory predefinita.
zm_b_remove_msg = Sei sicuro di voler rimuovere la cartella selezionata dal programma?{0}La cartella rimossa non verrà eliminata dal tuo computer.
zm_s_name = Nome cartella
zm_s_path = Percorso cartella
zm_s_count = Numero di file INI
zm_s_size = Dimensione totale
zm_h_row = Riga
zm_h_error_type = Tipo di errore
zm_h_key_section = Chiave / Sezione
zm_h_detailed_analysis = Analisi dettagliata
zm_e_info = Info
zm_e_select_pending = Selezione in sospeso
zm_e_select_pending_msg = Per visualizzare i risultati dell'analisi, seleziona una cartella dalla lista sopra.
zm_e_no_issue_detected = Nessun problema rilevato. Tutti i file sembrano a posto.
zm_e_no_issue = Nessun problema
zm_e_target_file_null = Non trovato in questi file: {0}
zm_e_missing_key = Chiave mancante
zm_e_file = File: {0}
zm_e_repeat_key = Chiave duplicata
zm_e_different_section = Differenze di sezione
zm_e_placeholder = Differenza segnaposto
zm_e_number = Differenza numero
zm_e_punctuation = Differenza punteggiatura
zm_e_quote = Differenza citazione
zm_ep_placeholder = Segnaposto
zm_ep_number = Numero
zm_e_row = Riga: {0}
zm_e_different_files = File diversi: {0}
zm_e_different_comment = Differenza nella riga di commento
zm_e_row_total = Totale righe {0}. Diverso dalle altre lingue.
zm_e_different_row_count = Differenza nel numero di righe
zm_e_error = Errore di analisi. Errore: {0}

[ZafuseGenReport]
zgr_pending_select_msg = Esegui prima un'analisi prima di generare il report, quindi riprova.
zgr_report_title = {0} - Risultati del report di analisi
zgr_analysis_path = Directory analizzata: {0}
zgr_version = Versione:
zgr_process_time = Tempo di elaborazione:
zgr_website = Sito Web:
zgr_github = GitHub:
zgr_donate = Dona:
zgr_save_directory = Seleziona la posizione per salvare
zgr_export_name = {0} - Report dei risultati dell'analisi - {1}
zgr_save_txt = Documento di testo
zgr_save_success = Il report dei risultati dell'analisi {0} è stato salvato con successo come '{1}'.
zgr_save_info_open = Vuoi aprire il file ora?
zgr_save_failed = Si è verificato un errore durante il salvataggio.{0}Errore: {1}

; SOFTWARE UPDATE
; ====================================================================

[SoftwareUpdate]
su_title = {0} - Controllo aggiornamenti
su_available = È disponibile una nuova versione per {0}!{1}La tua versione attuale: v{2}{3}Ultima versione: v{4}{5}Premi Sì per avviare la procedura guidata di aggiornamento TS e scaricare la nuova versione.
su_not_available = {0} è aggiornato.{1}Versione client: v{2}
su_newer = Congratulazioni!{0}Sei tra i primi a provare la versione {1}, che non è ancora stata rilasciata al pubblico!
su_ts_updater_c_running = La procedura guidata di aggiornamento TS è già in esecuzione. L'applicazione verrà ora chiusa...
su_ts_updater_not_available = Il file {0} non è stato trovato. Verrai reindirizzato alla pagina di download su GitHub...
su_not_connection = Impossibile completare il controllo degli aggiornamenti perché non è stata stabilita una connessione a Internet.{0}Controlla la connessione e riprova.
su_error = Si è verificato un errore durante il controllo degli aggiornamenti. Riprova più tardi.{0}Errore: {1}

; TS UPDATER
; ====================================================================

[TSUpdater]
tsu_title = {0} - Procedura guidata aggiornamenti {1} - {2}
tsu_subtitle = TS - Procedura guidata aggiornamenti
tsu_ui_loading = Caricamento...
tsu_ui_release_notes = Note di rilascio
tsu_version_not_installed = Attuale: non installato
tsu_app_default_name = Applicazione
tsu_status_checking = Controllo in corso...
tsu_status_ready_update = Pronto per aggiornamento o installazione.
tsu_status_ready_launch = Pronto per avviare l'applicazione.
tsu_status_downloading = Download in corso...
tsu_status_extracting = Estrazione dei file...
tsu_status_launching = Avvio dell'applicazione...
tsu_status_error = Si è verificato un errore. Riprova.
tsu_status_preparing = Preparazione in corso...
tsu_button_preparing = Preparazione...
tsu_button_launching = Avvio...
tsu_button_retry = Riprova
tsu_button_start_update = Avvia aggiornamento
tsu_button_start_install = Avvia installazione
tsu_button_start_app = Avvia applicazione
tsu_button_start = Avvia
tsu_substatus_checking_versions = Controllo delle versioni dell'applicazione...
tsu_substatus_download_starting = Avvio del download...
tsu_substatus_extracting_files = Estrazione dei file...
tsu_substatus_preparing_app = Preparazione all'avvio dell'applicazione...
tsu_substatus_please_wait = Attendere prego...
tsu_status_new_version_available = È disponibile una nuova versione per {0}!
tsu_status_ready_for_install = {0} è pronto per l'installazione.
tsu_status_app_up_to_date = {0} è aggiornato.
tsu_status_connecting_to_server = Connessione al server...
tsu_error_url_message = Impossibile generare l'URL di aggiornamento. Controlla le impostazioni.
tsu_error_timeout_message = Il server non ha risposto in tempo. Controlla la connessione Internet e riprova.
tsu_error_connection_message = Errore di connessione al server:
tsu_error_version_check_message = Errore di controllo versione:
tsu_error_download_url_message = URL di download non configurato o non generabile.
tsu_error_invalid_download_url = URL di download vuoto o non valido.
tsu_error_config_load = Impossibile caricare la configurazione dell'applicazione.
tsu_error_on_startup = Si è verificato un errore all'avvio dell'applicazione:
tsu_error_release_page_not_configured = URL della pagina delle note di rilascio non configurato.
tsu_error_open_release_page = Impossibile aprire la pagina delle note di rilascio:
tsu_error_download_message = Si è verificato un errore durante il download:
tsu_error_zip_not_found = File ZIP non trovato. Fai clic sul pulsante per riprovare.
tsu_error_extraction_failed = Installazione non completata. Fai clic sul pulsante per riprovare.
tsu_error_invalid_file_path = Rilevato percorso file non valido (Zip Slip prevenuto).
tsu_error_self_exe_update = Errore di aggiornamento dell'eseguibile:
tsu_error_extraction_files = Si è verificato un errore durante l'estrazione dei file:
tsu_error_during_operation = Si è verificato un errore durante l'operazione:
tsu_error_launch_app = Impossibile avviare l'applicazione:
tsu_error_launch_exception = Si è verificato un errore durante l'avvio dell'applicazione:
tsu_app_will_exit = Il programma verrà chiuso.
tsu_ask_view_release_notes = Vuoi visualizzare le note di rilascio pubblicate per {0}?{1}Le note di rilascio possono contenere modifiche importanti e informazioni da tenere presenti.
tsu_confirm_new_version = È disponibile una nuova versione per {0}.{1}Vuoi scaricare e installare la nuova versione?
tsu_confirm_install = {0} verrà scaricato e installato.{1}Vuoi continuare?
tsu_success_update_completed = {0} è stato aggiornato con successo.
tsu_success_install_completed = {0} è stato installato con successo.
tsu_prompt_launch_after_update = L'aggiornamento di {0} è completato. Vuoi avviare l'applicazione ora?
tsu_prompt_launch_app = Vuoi avviare {0} ora?
tsu_prompt_launch_after_install = L'installazione di {0} è completata. Vuoi avviare l'applicazione ora?
tsu_current_version_label = Attuale: {0}
tsu_exe_not_found = File eseguibile (.exe) non trovato. Controlla il percorso del file.
tsu_error_file_in_use = {0} è attualmente in esecuzione. Chiudi il programma aperto prima dell'aggiornamento.
tsu_online_version_label = Ultima versione: {0}
tsu_zip_not_found_error = File ZIP non trovato.
tsu_download_completed_label = scaricato
tsu_file_label = File:

; ABOUT
; ====================================================================

[SoftwareAbout]
sa_title = {0} - Informazioni
sa_website_link = Sito Web
sa_github_link = GitHub
sa_donate_link = Dona
sa_lang_name = Lingua
sa_lang_translator = Traduttore